spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=app
spring.datasource.password=app

server.port=8081

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=${app.kafka.consumer.group-id}
