ALTER SESSION SET CONTAINER = XEPDB1;

-- Índice para acelerar el conteo por criterios (hotel, fechas, hash de edades)
CREATE INDEX APPHOTEL.IDX_AVAIL_SEARCH_COUNT
    ON APPHOTEL.HOTEL_AVAILABILITY_SEARCHES (HOTEL_ID, CHECK_IN_DATE, CHECK_OUT_DATE, AGES_HASH);

COMMIT;
